DROP DATABASE IF EXISTS neverland;

CREATE DATABASE neverland;

use rabserve_VirtualGallery;

DROP TABLE IF EXISTS admin CASCADE;
DROP TABLE IF EXISTS artists CASCADE;
DROP TABLE IF EXISTS art CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS artOrders CASCADE;
DROP TABLE IF EXISTS mailingList CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE admin (

 adminId INT PRIMARY KEY AUTO_INCREMENT,
 username VARCHAR(255) UNIQUE NOT NULL,
 password VARCHAR(255) NOT NULL
);

CREATE TABLE artists (

 artistId INT PRIMARY KEY AUTO_INCREMENT,
 portrait VARCHAR(255) UNIQUE NOT NULL,
 bio BLOB NOT NULL,
 email VARCHAR(128) UNIQUE NOT NULL,
 phone VARCHAR(32) UNIQUE NOT NULL,
 name VARCHAR(255) NOT NULL
);

CREATE TABLE art (

 artId INT PRIMARY KEY AUTO_INCREMENT,
 artistId INT,
 name VARCHAR(255) NOT NULL,
 price NUMERIC(12,2) NOT NULL,
 description BLOB NOT NULL,
 stock INT NOT NULL,
 image VARCHAR(255) UNIQUE NOT NULL,

 FOREIGN KEY (artistId) REFERENCES artists(artistId) ON DELETE CASCADE,

 CONSTRAINT stock_check CHECK(stock >= 0),
 CONSTRAINT amt_check CHECK(amtSold >= 0),
 CONSTRAINT price_check CHECK(price >= 0)
);

CREATE TABLE orders (

 orderId INT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(255) NOT NULL,
 email VARCHAR(128) NOT NULL,
 phone VARCHAR(32),
 shippingCost NUMERIC(5,2) NOT NULL,
 address VARCHAR(255) NOT NULL,
 saleId INT NOT NULL,
 isFulfilled TINYINT(1) NOT NULL,

 CONSTRAINT shipping_check CHECK(shippingcost >= 0),
 CONSTRAINT fulfilled_check CHECK(isFulfilled >= 0)
);

CREATE TABLE artOrders (

 artId INT,
 orderId INT,

 CONSTRAINT pk_artOrders PRIMARY KEY (artId,orderId),
 FOREIGN KEY (artId) REFERENCES art(artId) ON DELETE CASCADE,
 FOREIGN KEY (orderId) REFERENCES orders(orderId) ON DELETE CASCADE
);

CREATE TABLE mailingList (

 listId INT PRIMARY KEY AUTO_INCREMENT,
 email VARCHAR(128) UNIQUE NOT NULL
);

CREATE TABLE comments (

 commentId INT PRIMARY KEY AUTO_INCREMENT,
 email VARCHAR(128) NOT NULL,
 name VARCHAR(255) NOT NULL,
 comment BLOB NOT NULL
);

GRANT ALL ON `neverland`.* to 'phpuser1'@'localhost';

SET PASSWORD FOR 'phpuser1'@'localhost' = PASSWORD('c!ALedD54WwTcGqE3x9?p#^d?qxM@T6cp$#BCJcC2N+HRyb26DwDtgD8q#DpHR_msF7Jw#F@CAZj=*xCmr5*buGD4Ghak?Er*v!r@r$2N6wmhuchvuf@*3VmMfpX6Chy@^*6!2nrtkmnFbapE5VBAnSrpmjBp7ftQceKWJ!wzx#6jd3aJ8AtkaTX*UE+mEES!AGFtHEHZeGE4%scrcN$h%5*uddqQ6ywtr7TrG!#9ThgQmHT?g^8Ytvkaz');